export const list = [
  {
    image: "/images/refined.webp",
    name: "Fortune Refined",
    price: 78,
    mrp: 170,
  },
  {
    image: "/images/snacks/br-cake.webp",
    name: "Britannia Cake",
    price: 78,
    mrp: 170,
  },
  { image: "/images/colgate.webp", name: "Colgate", price: 78, mrp: 170 },
  { image: "/images/melody.webp", name: "Melody", price: 78, mrp: 170 },
  {
    image: "/images/mustard-oil.webp",
    name: "Mustard oil",
    price: 78,
    mrp: 170,
  },
  { image: "/images/packedFood/poha.webp", name: "Poha", price: 78, mrp: 170 },
  {
    image: "/images/snacks/punjabi-tadka.webp",
    name: "Punjabi Tadka",
    price: 78,
    mrp: 170,
  },
  { image: "/images/sugar.webp", name: "Sugar", price: 78, mrp: 170 },
  { image: "/images/snacks/All-in-one.webp", name: "All In One", price: 78, mrp: 170 },
  { image: "/images/red-label.webp", name: "Red Label", price: 78, mrp: 170 },
  { image: "/images/snacks/chocolush.webp", name: "Chocolush", price: 78, mrp: 170 },
  {
    image: "/images/snacks/dark-fantasy.webp",
    name: "Dark Fantasy",
    price: 78,
    mrp: 170,
  },
  {
    image: "/images/snacks/real-mix-bottle.webp",
    name: "Real Mix Juice",
    price: 78,
    mrp: 170,
  },
  { image: "/images/snacks/thumsup.webp", name: "ThumsUp", price: 78, mrp: 170 },
];
