// // categoryData.js


// export const categoryData = {
//   staples: {
//     title: "Staples",
//     image: [
//       {
//         image: "/images/staples/arhar.jpg",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/staples/rajma.jpeg",
//         name: "Rajma",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/staples/moong_dal.jpg",
//         name: "Moong Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/staples/masoor_dal.jpg",
//         name: "Masoor Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/staples/chana_dal.webp",
//         name: "Chana Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/staples/chick_pea.jpeg",
//         name: "Kabuli Chana",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/staples/urad_dal.png",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//     ],
//   },
//   snacks: {
//     title: "Snacks & Beverages",
//     image: [
//       {
//         image: "/images/snacks/ChocoPie.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/All-in-one.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/br-cake.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/dark-fantasy.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/gupshup.webp",
//         name: "Moong Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/Lays.webp",
//         name: "Masoor Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/masalaPeanut.webp",
//         name: "Chana Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/Navratan.webp",
//         name: "Kabuli Chana",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/Oreo.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/parleG.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/Popcorn.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/punjabi-tadka.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/real-mix-bottle.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/thumsup.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/tooYumm.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/uncleChips.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/snacks/yogaBar.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//     ],
//   },
//   packedFood: {
//     title: "Packaged Food",
//     image: [
//       {
//         image: "/images/packedFood/BambinoPasta.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/chings.webp",
//         name: "Rajma",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/chocos.webp",
//         name: "Moong Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/cornFlakes.webp",
//         name: "Masoor Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/maggi.webp",
//         name: "Chana Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/maggiPasta.webp",
//         name: "Kabuli Chana",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/noodles.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/oats.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/papad.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/poha.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/yippee.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/yippeePasta.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/packedFood/yu.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//     ],
//   },
//   personalCare: {
//     title: "Personal & Baby Care",
//     image: [
//       {
//         image: "/images/personalCare/dettolbw.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/personalCare/dettolhw.webp",
//         name: "Rajma",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/personalCare/dettolSoap.webp",
//         name: "Moong Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/personalCare/fair&handsomefw.webp",
//         name: "Masoor Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/personalCare/garnierfw.webp",
//         name: "Chana Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/personalCare/luxbw.webp",
//         name: "Kabuli Chana",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/personalCare/pearsSoap.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//     ],
//   },
//   household: {
//     title: "Household Care",
//     image: [
//       {
//         image: "/images/household/ariel-detergent.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/household/comfort-conditioner.webp",
//         name: "Rajma",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/household/henkobar.webp",
//         name: "Moong Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/household/morelight.webp",
//         name: "Masoor Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/household/surfexcel-5kg.webp",
//         name: "Chana Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/household/surfexcel-500g.webp",
//         name: "Kabuli Chana",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/household/tide-5kg.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//     ],
//   },
//   dairy: {
//     title: "Dairy & Eggs",
//     image: [
//       {
//         image: "/images/dairy/amul-cream.webp",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/dairy/amul-kool.webp",
//         name: "Rajma",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/dairy/amul-lassi.webp",
//         name: "Moong Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/dairy/amul-masti.webp",
//         name: "Masoor Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/dairy/amul-taza.webp",
//         name: "Chana Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/dairy/hersheysChoco.webp",
//         name: "Kabuli Chana",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/dairy/milkmaid.webp",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//     ],
//   },
//   home: {
//     title: "Home & Kitchen",
//     image: [
//       {
//         image: "/images/home/bucket-mug.jpg",
//         name: "Arhar Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/home/bucket.jpeg",
//         name: "Rajma",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/home/dustbin.webp",
//         name: "Moong Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/home/jar.webp",
//         name: "Masoor Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/home/knife.jpeg",
//         name: "Chana Dal",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/home/stand.webp",
//         name: "Kabuli Chana",
//         price: 78,
//         mrp: 170,
//       },
//       {
//         image: "/images/home/tokri.jpeg",
//         name: "Urad Dal",
//         price: 78,
//         mrp: 170,
//       },
//     ],
//   },
// };

// categoryData.js


export const categoryData = [
  {
    title: "Staples",
    type: "staples",
    image: [
      {
        image: "/images/staples/arhar.jpg",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/staples/rajma.jpeg",
        name: "Rajma",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/staples/moong_dal.jpg",
        name: "Moong Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/staples/masoor_dal.jpg",
        name: "Masoor Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/staples/chana_dal.webp",
        name: "Chana Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/staples/chick_pea.jpeg",
        name: "Kabuli Chana",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/staples/urad_dal.png",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
    ],
  },
  {
    title: "Snacks & Beverages",
    type:"snacks",
    image: [
      {
        image: "/images/snacks/ChocoPie.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/All-in-one.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/br-cake.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/dark-fantasy.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/gupshup.webp",
        name: "Moong Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/Lays.webp",
        name: "Masoor Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/masalaPeanut.webp",
        name: "Chana Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/Navratan.webp",
        name: "Kabuli Chana",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/Oreo.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/parleG.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/Popcorn.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/punjabi-tadka.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/real-mix-bottle.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/thumsup.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/tooYumm.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/uncleChips.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/snacks/yogaBar.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
    ],
  },
  {
    title: "Packaged Food",
    type:"packedFood",
    image: [
      {
        image: "/images/packedFood/BambinoPasta.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/chings.webp",
        name: "Rajma",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/chocos.webp",
        name: "Moong Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/cornFlakes.webp",
        name: "Masoor Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/maggi.webp",
        name: "Chana Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/maggiPasta.webp",
        name: "Kabuli Chana",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/noodles.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/oats.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/papad.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/poha.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/yippee.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/yippeePasta.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/packedFood/yu.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
    ],
  },
  {
    title: "Personal & Baby Care",
    type:"personalCare",
    image: [
      {
        image: "/images/personalCare/dettolbw.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/personalCare/dettolhw.webp",
        name: "Rajma",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/personalCare/dettolSoap.webp",
        name: "Moong Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/personalCare/fair&handsomefw.webp",
        name: "Masoor Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/personalCare/garnierfw.webp",
        name: "Chana Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/personalCare/luxbw.webp",
        name: "Kabuli Chana",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/personalCare/pearsSoap.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
    ],
  },
  {
    title: "Household Care",
    type:"household",
    image: [
      {
        image: "/images/household/ariel-detergent.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/household/comfort-conditioner.webp",
        name: "Rajma",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/household/henkobar.webp",
        name: "Moong Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/household/morelight.webp",
        name: "Masoor Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/household/surfexcel-5kg.webp",
        name: "Chana Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/household/surfexcel-500g.webp",
        name: "Kabuli Chana",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/household/tide-5kg.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
    ],
  },
  {
    title: "Dairy & Eggs",
    type:"dairy",
    image: [
      {
        image: "/images/dairy/amul-cream.webp",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/dairy/amul-kool.webp",
        name: "Rajma",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/dairy/amul-lassi.webp",
        name: "Moong Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/dairy/amul-masti.webp",
        name: "Masoor Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/dairy/amul-taza.webp",
        name: "Chana Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/dairy/hersheysChoco.webp",
        name: "Kabuli Chana",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/dairy/milkmaid.webp",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
    ],
  },
  {
    title: "Home & Kitchen",
    type:"home",
    image: [
      {
        image: "/images/home/bucket-mug.jpg",
        name: "Arhar Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/home/bucket.jpeg",
        name: "Rajma",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/home/dustbin.webp",
        name: "Moong Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/home/jar.webp",
        name: "Masoor Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/home/knife.jpeg",
        name: "Chana Dal",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/home/stand.webp",
        name: "Kabuli Chana",
        price: 78,
        mrp: 170,
      },
      {
        image: "/images/home/tokri.jpeg",
        name: "Urad Dal",
        price: 78,
        mrp: 170,
      },
    ],
  },
];
